### ISSUE TITLE
Issue with Path Display in Library for Long Paths

### ISSUE THREAD

**Issue by hkhk368** [kikijiki/ntfs-reader#1]
@kikijiki 
First of all, thank you for sharing your code. However, I've encountered a bug in the library related to path display. When the path is relatively long, the full path is not properly shown in the 'path' field.

Please refer to the following test case. There is an issue when retrieving the path for each record in the MFT; the path does not include the disk header and the first-level folder. Here is an example for your reference.

```
info!("======== Testing WITH cache (Vec) ========");
        {
            let mut files = Vec::new();
            files.reserve(mft.max_record as usize);

            let mut cache = VecCache::default();
            cache.0.resize(mft.max_record as usize, PathBuf::new());

            info!("Iteration start");
            let start_time = Instant::now();
            let mut counter = 0usize;
            mft.iterate_files(|file| {
                let x = FileInfo::with_cache(&mft, &file, &mut cache);
                if x.is_directory {
                    files.push(x);
                }
                counter += 1;
            });

            info!("Dropping cache");
            drop(cache);

            info!(
                "Read all {} records in {:?}",
                counter,
                Instant::now() - start_time
            );

            for xx in files {
                let y = xx.path.to_str().unwrap();
                if !y.starts_with("\\") {
                    println!("{:?}", y);
                }
            }
```
            
            
            
            
**Below is an example of the output. As you can see, these paths are incomplete, lacking information such as the drive letter.**
"GoLand\\bin\\goland.svg"
"GoLand\\bin\\WinProcessListHelper.exe"
"GoLand\\bin\\WinShellIntegrationBridge.dll"
"GoLand\\bin\\brokenPlugins.db"
"GoLand\\bin\\defender-exclusions.ps1"

**Comment by kikijiki** [comment]
Hey thanks for the feedback.
I'll take a look at the issue and see if I can fix it 👍

**Comment by hkhk368** [comment]
> Hey thanks for the feedback. I'll take a look at the issue and see if I can fix it 👍

Sure. Many thanks for your help.

**Comment by kikijiki** [comment]
I can't seem to reproduce the issue on my machine, what's the full path of those wrong paths?

**Comment by hkhk368** [comment]
> "GoLand\bin\goland.svg"

Thank you for your kind assistance.

I have encountered an error with recording paths in my directory: "D:\IDE"

This path contains numerous software installations, including GoLand, Miniconda3, PyCharm, RustRover, and many others, resulting in a large number of files in this folder. I suspect that the error is due to an excessive number of files in a single folder. When I use your library, files under this folder lose the "D:\IDE" part of their path. For instance, as mentioned above, the result only shows "GoLand\bin\goland.svg" while its complete path is actually “D:\IDE\GoLand\bin\goland.svg". Another example is that the path “D:\IDE\miniconda3\envs\news\Lib\site-packages\torch\include\ATen\ops\logaddexp_meta_dispatch.h” is only displayed as "miniconda3\envs\news\Lib\site-packages\torch\include\ATen\ops\logaddexp_meta_dispatch.h".


I have also listed all the files in this folder for your reference. Please see the attached file. Thank you.
[file_paths.csv](https://github.com/kikijiki/ntfs-reader/files/13773815/file_paths.csv)

**Comment by hkhk368** [comment]
@kikijiki Following up on my previous message, I've also tried with front-end projects. As you know, front-end projects often have a large number of files in the 'node_modules' directory. I placed several different front-end projects in the 'D:\project' folder. I then used your library again to read all the MFT records, and the same issue occurred - the 'D:\project' directory was missing. It seems that when a folder contains too many files, it causes problems.

A simple way to reproduce this error is by using the CSV file I provided earlier. You can use a script to automatically create some files with content in the paths indicated in the CSV. This should replicate my issue. Alternatively, installing software like Goland or PyCharm in the same directory can also reproduce this problem. Thank you.

**Comment by kikijiki** [comment]
Not sure if it fixes your issue but, I updated the code so now I process attribute lists too.
It should pick up names that it used to skip.

**Comment by hkhk368** [comment]
@kikijiki Thank you very much for your help, but unfortunately, this still does not solve my problem.

Below is my code, I had it print out the path, but there's still an issue.
```
test_iteration("No Cache", &mft, |mft: &Mft, file: &NtfsFile| {
let x = FileInfo::new(mft, file);
println!("{:?}", x.path.to_str());
x
})?;
```
It's okay, I've decided to return to C language. I plan to create a library using C language for the MFT reading part (of course, I haven't started writing it yet, I am currently looking for implementations of MFT reading in C language), and then use this C language library in RUST.

**Comment by tuolaji123** [comment]
I don't know if the issue has been resolved now. I have already solved it. The issue was in file_info.rs. But I don't know how to send the code as an attachment.

**Comment by tuolaji123** [comment]
[file_info.txt](https://github.com/kikijiki/ntfs-reader/files/13991541/file_info.txt)
Download the .txt file, rename it to .rs, and it contains detailed comments. Just replace file_info.rs with it.

**Comment by hkhk368** [comment]
> I don't know if the issue has been resolved now. I have already solved it. The issue was in file_info.rs. But I don't know how to send the code as an attachment.

This issue remains unresolved. You can copy and paste the source code file into this GitHub edit box, and GitHub will automatically upload the file. Alternatively, you can click on the 'attach files' in the top right corner of the edit box to upload the file, or you can directly copy and paste the source code plain text file here.

**Comment by hkhk368** [comment]
> [file_info.txt](https://github.com/kikijiki/ntfs-reader/files/13991541/file_info.txt) Download the .txt file, rename it to .rs, and it contains detailed comments. Just replace file_info.rs with it.

Thank you. This perfectly solved my problem. You are very helpful.

**Comment by kikijiki** [comment]
@tuolaji123 Hey thanks for fixing whatever was the issue.
I didn't check the content yet but, could you make a PR so I can merge?
Or I can add the fix directly if you prefer, let me know.

**Comment by kikijiki** [comment]
@tuolaji123 So the problem is that some relative path appears in the file names?
Can you tell me what gets returned in the `components` for those problematic files?
Maybe there is a `..` or something returned by `get_best_file_name().to_string()`?

In your code it looks like you are making sure the paths returned from the cache are absolute, but `cache.insert()` disappeared so I think the cache is just being bypassed. As a test you could check if the non cached version works ok.

Ideally the paths should be validated before caching them, so that we can keep the existing behavior (on cache hit break from the loop and append the remaining components on top).
Maybe adding `canonicalize()` before the insert could fix the issue.

**Comment by kikijiki** [comment]
Ok got some time to investigate it and it was a very dumb thing 😅 .
The `VecCache` was initialized with `PathBuf::new()` instead of `None`, so it caused every cache check to succeed with an empty path.
I updated the `VecCache` definition to use `Option<PathBuf>` instead.
